table Calendario
	lineageTag: b429dc76-e12f-421d-bb92-7556f6e7cf41

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 643d95f2-736b-4a51-bc6e-de68f1081928
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 2696168f-3680-4248-a611-498c4a37c0d4
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		lineageTag: 9214fb7f-894f-476e-8c6c-3abd6778b3f6
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 1c5a3df9-3583-4c3e-9e63-ac7d5678447a
		summarizeBy: none
		sourceColumn: MonthName

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 7ba616b2-7168-4327-b8de-6152873cbbc1
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	partition Calendario = m
		mode: import
		queryGroup: Calendario
		source =
				let
				    // Datos de referencia — tu tabla de ejecuciones
				    SourceFact = #"etls_ejecutadas",
				    // Fecha mínima y máxima de los datos
				    MinDate = Date.From( List.Min(SourceFact[fecha_inicio]) ),
				    MaxDate = Date.From( List.Max(SourceFact[fecha_inicio]) ),
				    // Generar lista de fechas entre MinDate y MaxDate
				    Fechas = List.Dates( MinDate, Duration.Days(MaxDate - MinDate) + 1, #duration(1,0,0,0) ),
				    FechaTable = Table.FromList(Fechas, Splitter.SplitByNothing(), {"Date"}),
				    DateTyped = Table.TransformColumnTypes(FechaTable, {{"Date", type date}}),
				    // Añadir columnas de año, mes, trimestre, etc.
				    AddYear = Table.AddColumn(DateTyped, "Year", each Date.Year([Date]), Int64.Type),
				    AddMonth = Table.AddColumn(AddYear, "Month", each Date.Month([Date]), Int64.Type),
				    AddMonthName = Table.AddColumn(AddMonth, "MonthName", each Date.ToText([Date], "MMMM"), type text),
				    AddQuarter = Table.AddColumn(AddMonthName, "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date])), type text)
				in
				    AddQuarter

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

